name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: ["*"]

  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Bun environment
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install Dependencies
        run: bun install
      - name: typecheck
        run: bun run tsc
      - name: build
        run: bun run build
      - name: format check
        run: bun run format:check
      - name: test
        run: bun run test
